// ----------------------
// <auto-generated>
//     generated using a custom program
// </auto-generated>
// ----------------------

export interface CPrem {
    Acre: string | null;
    Applies: string | null;
    AttachId: string;
    AttachType: number;
    ChangedBy: string | null;
    ChangedDate: string;
    CLocId: string | null;
    Code: string | null;
    CoInsPct: string | null;
    Cost: Partial<number> | null;
    Coverage: string | null;
    CovGroup: number | null;
    CovLevel: string | null;
    CPremId: string;
    CrimeRateGrp: string | null;
    DatabaseName: string | null;
    DaysPerRest: string | null;
    DedBasis: string | null;
    DedDiscPrem: number | null;
    DedType: string | null;
    DedType2: string | null;
    DedType3: string | null;
    Deduct: number | null;
    Deduct2: number | null;
    Deduct3: number | null;
    EffDate: string;
    EmpBenRmkCPrem: string | null;
    EmpCovered: string | null;
    EnteredDate: string;
    EquipLevel: string | null;
    Exposure: string | null;
    FormsCond: string | null;
    Franchise: string | null;
    FullTimeEmp: string | null;
    Id: number;
    iLimit1: number | null;
    iLimit2: number | null;
    iLimit3: number | null;
    iLimit4: number | null;
    InflationGuard: string | null;
    InsertSeqNo: number;
    InsLossPartic: number | null;
    IsCommunication: string | null;
    IsContributionLoc: string | null;
    IsDayCare1To3: string | null;
    IsInservant: string | null;
    IsLeaderLoc: string | null;
    IsManufacturingLoc: string | null;
    IsOnApp: string | null;
    IsOutServant: string | null;
    IsPower: string | null;
    IsRecipientLoc: string | null;
    IsRefigMaintenance: string | null;
    IsSeasonal: string | null;
    IsWater: string | null;
    LimitLossPay: string | null;
    LobId: string;
    Misc: string | null;
    NumOf: string | null;
    NumOfHead: string | null;
    PartTimeEmp: string | null;
    Payroll: Partial<number> | null;
    PolId: string;
    Premium: Partial<number> | null;
    Rate: number | null;
    RatingBasis: string | null;
    Receipts: Partial<number> | null;
    ResidentEmp: string | null;
    RetroDate: string | null;
    Sales: Partial<number> | null;
    SortNo: number | null;
    State: string | null;
    Status: string | null;
    Territory: string | null;
    TotalAssetValue: number | null;
    Type: string | null;
    Valuation: string | null;
    vLimit1: string | null;
    vLimit2: string | null;
    vLimit3: string | null;
    vLimit4: string | null;
    WaitingPeriod: number | null;
    Zone: number | null;
}

export interface GeneralLedgerPeriod {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    Description: string | null;
    EndDate: string;
    EnteredDate: string;
    FiscalPeriod: string | null;
    FiscalYear: string | null;
    GLDivCode: string | null;
    Id: number;
    StartDate: string;
}

export interface Vendor {
    Addr1: string | null;
    Addr2: string | null;
    BusAreaCode: string | null;
    BusExt: string | null;
    BusPhone: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    Contact: string | null;
    ContactAreaCode: string | null;
    ContactExt: string | null;
    ContactPhone: string | null;
    DatabaseName: string | null;
    Description: string | null;
    EIN: string | null;
    EMail: string | null;
    EnteredDate: string;
    FaxAreaCode: string | null;
    FaxExt: string | null;
    FaxPhone: string | null;
    FirstName: string | null;
    GLNumber: string | null;
    Id: number;
    IsCompany: string | null;
    IsHide: string | null;
    LastName: string | null;
    Memo: string | null;
    MidName: string | null;
    MobileAreaCode: string | null;
    MobileExt: string | null;
    MobilePhone: string | null;
    S1099Category: number | null;
    S1099Type: number | null;
    ShortName: string | null;
    State: string | null;
    Terms: string | null;
    VendorCode: string | null;
    WebAddr: string | null;
    ZipCode: string | null;
}

export interface InvoiceBillingEvent {
    BHId: string;
    BillingDate: string | null;
    BillSeqId: string;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredBy: string | null;
    EnteredDate: string;
    EventSource: string | null;
    EventType: string | null;
    Id: number;
    InvBEId: string;
    InvId: string | null;
    SuspensionInfo: string | null;
    Text: string | null;
}

export interface SetupBillingTran {
    AgyCommFlag: string | null;
    BrokerCommFlag: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    ChargeCat: string | null;
    ChargeCode: string | null;
    ChargeDesc: string | null;
    DatabaseName: string | null;
    EnteredDate: string;
    ExecCommFlag: string | null;
    Id: number;
    IncomeGrp: string | null;
    IsHide: string | null;
    LinkedPremium: string | null;
    NonPrFlRate: Partial<number> | null;
    NonPrGlAcct1: string | null;
    NonPrGlAcct2: string | null;
    NonPrInstTreat: string | null;
    NonPrMethod: string | null;
    NonPrPercent: number | null;
    NonPrRecipient: string | null;
    PermFlag: number;
    RepCommFlag: string | null;
    ReportDesc: string | null;
    SalesCntrCommFlag: string | null;
    ShortName: string | null;
    TranTypeDL: string | null;
}

export interface Submission {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    Id: number;
    PolId: string;
    SubGrId: string;
    SubmId: string;
}

export interface SubmissionGroup {
    ChangedBy: string | null;
    ChangedDate: string;
    CustId: string;
    DatabaseName: string | null;
    EnteredDate: string;
    GroupNo: string | null;
    Id: number;
    SubGrId: string;
}

export interface VendorInvoice {
    BankCode: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    Description: string | null;
    EnteredDate: string;
    GLDivCode: string | null;
    Id: number;
    JournalTranId: string | null;
    Notes: string | null;
    PONo: string | null;
    PostDate: string | null;
    RefNo: number | null;
    Status: string | null;
    VendorCode: string | null;
    VenDueDate: string;
    VenPayDate: string;
    VInvDate: string;
    VInvEnteredBy: string | null;
    VInvEnteredDate: string | null;
    VInvId: string;
    VInvNo: string | null;
    VInvPayAmt: Partial<number>;
    VInvTotAmt: Partial<number>;
    VInvVoidDate: string | null;
    VInvVoidedBy: string | null;
    VInvVoidReason: string | null;
    VITId: string | null;
    VoidJournalTranId: string | null;
    VoidRefNo: number | null;
}

export interface VoidedCheck {
    CDid: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    Id: number;
    PCid: string | null;
    VCid: string;
    VoidDate: string | null;
    VoidedBy: string | null;
    VoidReason: string | null;
}

export interface PrintedCheck {
    BankCode: string | null;
    CDid: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CheckNo: number;
    CheckNoAssignDate: string | null;
    DatabaseName: string | null;
    EnteredDate: string;
    Id: number;
    PCid: string;
    PrintedBy: string | null;
    VCid: string | null;
}

export interface BankAccount {
    AccountType: string | null;
    AreaCode: string | null;
    BankAcctNo: string | null;
    BankAdd1: string | null;
    BankAdd2: string | null;
    BankCity: string | null;
    BankCode: string | null;
    BankName: string | null;
    BankState: string | null;
    BankZip: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    ConvClearedTotAmt: Partial<number> | null;
    ConvOpenAmt: Partial<number> | null;
    DatabaseName: string | null;
    DefCheckNo: string | null;
    EnteredDate: string;
    Extension: string | null;
    FaxAreaCode: string | null;
    FaxExt: string | null;
    FaxPhone: string | null;
    GLDivCode: string | null;
    GLNumber: string | null;
    Id: number;
    IsHandWriteOnly: string | null;
    IsHide: string | null;
    NextCheckNo: string | null;
    Notes: string | null;
    PhoneNo: string | null;
    RoutingNo: string | null;
    SecurityGroup: string | null;
    ShortName: string | null;
    WebAddr: string | null;
}

export interface PayStatementDetail {
    AgcyComm: Partial<number>;
    AgcyGross: Partial<number>;
    AgcyPercent: number | null;
    AmtPaidStmt: Partial<number>;
    AmtPaidToDate: Partial<number>;
    BillMethod: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    ChargeCat: string | null;
    ChargeCode: string | null;
    CustId: string;
    DatabaseName: string | null;
    EnteredDate: string;
    GLTTranDate: string | null;
    Id: number;
    InvCmId: string | null;
    InvCoId: string;
    InvId: string;
    InvTPId: string;
    LineOfBus: string | null;
    Method: string | null;
    OffSetWithNoEffect: string | null;
    Payable: Partial<number>;
    PayableBal: Partial<number>;
    Percentage: number | null;
    PlanType: string | null;
    PolId: string;
    PrimaryBrokerCode: string | null;
    PrimaryExecCode: string | null;
    PrimaryRepCode: string | null;
    PSDId: string;
    Sort1By: string | null;
    Sort2By: string | null;
    TranType: string | null;
    WritingCoCode: string | null;
}

export interface PayStatementHeader {
    AttachType: number | null;
    CDId: string | null;
    CDPayBy: string | null;
    CDPayDate: string | null;
    CDPayStatus: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CRDId: string | null;
    CustId: string | null;
    DatabaseName: string | null;
    Description: string | null;
    EnteredDate: string;
    FilterOffsetting: string | null;
    GJId: string | null;
    GLDivCode: string | null;
    Id: number;
    IncBasis: string | null;
    IncBeginBalInv: string | null;
    IncBinders: string | null;
    IncBnPartPdUnPdPSH: string | null;
    IncBnPdInFull: string | null;
    IncCoPartPdUnPdPSH: string | null;
    IncCoPdInFull: string | null;
    IncDBPartRecUnRecPSH: string | null;
    IncDBRecItems: string | null;
    IncInsPartPdPSH: string | null;
    IncInsPartPdUnPdPSH: string | null;
    IncInsPdInFull: string | null;
    IncInsUnPdPSH: string | null;
    IsAmtDefaulted: string | null;
    IsProRatedAmtDefaulted: string | null;
    IsReadyPayDefaulted: string | null;
    MasterAgent: string | null;
    PSHId: string;
    S1099CategoryPSH: number | null;
    S1099TypePSH: number | null;
    Sort1By: string | null;
    Sort2By: string | null;
    StmtDate: string;
    StmtForCode: string | null;
    StmtForType: string | null;
    StmtSource: string | null;
    TotAgcyComm: Partial<number>;
    TotAgcyGross: Partial<number>;
    TotAmtPaidStmt: Partial<number>;
    TotPayable: Partial<number>;
    TotPayableBal: Partial<number>;
    TranThruDate: string;
}

export interface RefGroup {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    EntityId: string | null;
    EntityType: number;
    GroupType: string | null;
    Id: number;
    IsActive: string | null;
    LastChangedBy: string | null;
    LastChangedDate: string;
    Name: string | null;
    RefGrId: string;
}

export interface Suspense {
    ChangedBy: string | null;
    ChangedDate: string;
    CoCode: string | null;
    CompletedBy: string | null;
    CompletedDate: string | null;
    DatabaseName: string | null;
    DBAction: string | null;
    DescriptSusp: string | null;
    DueDate: string;
    EffDate: string | null;
    EnteredDate: string;
    EntityId: string | null;
    EntityType: number;
    Id: number;
    InitiatDate: string | null;
    LastExported: string | null;
    OutlookId: string | null;
    PolId: string | null;
    Priority: number;
    RefId: string | null;
    RefType: number | null;
    ReschedNo: number | null;
    Status: number;
    SuspByEmpCode: string | null;
    SuspId: string;
    SuspToEmpCode: string | null;
}

export interface Agency {
    ABBillMethod: string | null;
    AccountingBasis: string | null;
    AComRank1: number;
    AComRank2: number;
    AComRank3: number;
    AComRank4: number;
    AComRank5: number;
    AgencyId: string;
    AgencyNo: string | null;
    AMSBenefitsAgencyNo: string | null;
    AMSBenefitsPassword: Array<string> | null;
    AuthMode: string | null;
    AutoApplyPay: string | null;
    BillDaysInAdvance: number | null;
    BinderPostMethod: string | null;
    BrokStmtAddr: number | null;
    CashBasisRecognition: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CheckAddr: number | null;
    ClaimsAddr: number | null;
    CommFormsAddr: number | null;
    CStmtPaperSelection: string | null;
    CustReceivableAge1: number | null;
    CustReceivableAge2: number | null;
    CustReceivableAge3: number | null;
    CustReceivableAge4: number | null;
    CustStmtAddr: number | null;
    DatabaseName: string | null;
    DBBillMethod: string | null;
    DBInvoicing: string | null;
    DBThresholdAmt: Partial<number>;
    DComRank1: number;
    DComRank2: number;
    DComRank3: number;
    DComRank4: number;
    DComRank5: number;
    DefaultOperatingBankAgen: string | null;
    DefaultTrustBankAgen: string | null;
    DueDateBasis: string | null;
    DueDateBasisValue: number;
    EnteredDate: string;
    FinCenterSummary: string | null;
    FormLetterSchedAddr: number | null;
    GLDivCode: string | null;
    GlobalTenantId: string | null;
    GroupingOption: string | null;
    Id: number;
    IncludeBranch: string | null;
    IncludeGroup: string | null;
    InterDivAcctgActive: string | null;
    InterDivAcctgGLNumber: string | null;
    InterDivGLNumber: string | null;
    InvoiceAddr: number | null;
    InvPaperSelection: string | null;
    IsCustomerSearchResultsFiltered: string | null;
    IsHosted: string | null;
    IsPrintAgencyBill: string | null;
    IsPrintDirectBill: string | null;
    IvansUsagecategory: string | null;
    LateCharge: string | null;
    Latitude: number | null;
    LCAnnualPercent: number | null;
    LCDaysBeforeFirst: number | null;
    LCDesc: string | null;
    LCMinimum: Partial<number> | null;
    LCPeriodFlatRate: Partial<number> | null;
    LCThreshold: Partial<number> | null;
    Longitude: number | null;
    LossNoticeAddr: number | null;
    MachineAddr: string | null;
    MultiLineAddr: number | null;
    Name: string | null;
    NonPropertyAddr: number | null;
    NoOfUsersAMSCA: number;
    PartCode: string | null;
    PersFormsAddr: number | null;
    PremOption: string | null;
    PrintDueDateOnInvoice: string | null;
    PrintExecOnInvoice: string | null;
    PrintRepOnInvoice: string | null;
    ServerTimeZone: string | null;
    SiteDbServer: string | null;
    SmallBalThreshold: Partial<number> | null;
    SplitInvoice: string | null;
    SSOMigrationReady: string | null;
    Status: string | null;
    UseCOAByDiv: string | null;
    UseDiffFYByDiv: string | null;
    UseDiffLCByDiv: string | null;
    VendorAccountingBasis: string | null;
    VertaforeLocalStoreRoot: string | null;
}

export interface AgencyNotation {
    ANotId: string;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    Description: string | null;
    EnteredDate: string;
    Id: number;
    IsHide: string | null;
    NotationType: string | null;
    PermFlag: number;
}

export interface Broker {
    Addr1: string | null;
    Addr2: string | null;
    ARClosedDate: string;
    ARClosedStatus: string | null;
    BJEClosedStatus: string | null;
    BrokerCode: string | null;
    BusAreaCode: string | null;
    BusExt: string | null;
    BusFullPhone: string | null;
    BusPhone: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    Contact: string | null;
    DatabaseName: string | null;
    EmailBrok: string | null;
    EnteredDate: string;
    FaxAreaCode: string | null;
    FaxExt: string | null;
    FaxFullPhone: string | null;
    FaxPhone: string | null;
    FirstName: string | null;
    Id: number;
    IsCompany: string | null;
    IsHide: string | null;
    LastName: string | null;
    MidName: string | null;
    MobileAreaCode: string | null;
    MobileExt: string | null;
    MobileFullPhone: string | null;
    MobilePhone: string | null;
    NetFlag: string | null;
    ResAreaCode: string | null;
    ResExt: string | null;
    ResFullPhone: string | null;
    ResPhone: string | null;
    S1099Category: number | null;
    S1099Type: number | null;
    ShortName: string | null;
    State: string | null;
    StatePrintGroup: string | null;
    Status: string | null;
    TaxID: string | null;
    WebAddr: string | null;
    Zip: string | null;
}

export interface PolicyTranPremium {
    BilledPremium: Partial<number>;
    ChangedBy: string | null;
    ChangedDate: string;
    ChargeCatPolTP: string | null;
    ChargeCodePolTP: string | null;
    CoCodePolTP: string | null;
    CoTypePolTP: string | null;
    DatabaseName: string | null;
    DescriptionPolTP: string | null;
    EffDate: string;
    EnteredDate: string;
    FullTermPremium: Partial<number>;
    HowBilled: string | null;
    Id: number;
    IncludePremium: string | null;
    InsertSeqNo: number;
    IsCorrected: string | null;
    IsPosted: string | null;
    IsSuspended: string | null;
    LineOfBus: string | null;
    NonPrinstTreatPolTP: string | null;
    NonPrRecipientPolTP: string | null;
    PlanType: string | null;
    PolId: string;
    PolTPId: string;
    Premium: Partial<number>;
    Reconciled: string | null;
    TiComId: string | null;
    WritingCoCode: string | null;
    WrittenPremium: Partial<number>;
}

export interface GeneralLedgerAccounts {
    AccountReqFlag: string | null;
    AccountSubFlag: string | null;
    AccountType: string | null;
    BrokerageReqFlag: string | null;
    BrokerageSubFlag: string | null;
    BrokerReqFlag: string | null;
    BrokerSubFlag: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CommPersReqFlag: string | null;
    CommPersSubFlag: string | null;
    CompanyReqFlag: string | null;
    CompanySubFlag: string | null;
    ConsolAccount: string | null;
    DatabaseName: string | null;
    Description: string | null;
    EnteredDate: string;
    FeeReqFlag: string | null;
    FeeSubFlag: string | null;
    FinanceReqFlag: string | null;
    FinanceSubFlag: string | null;
    GLNumber: string | null;
    GroupSubTotals: string | null;
    Id: number;
    InvoiceReqFlag: string | null;
    IsHide: string | null;
    LevelNumber: number;
    OnAccountFlag: string | null;
    PermFlag: number;
    PolicyReqFlag: string | null;
    ReservedFlagGLCA: string | null;
    StmtFlag: string | null;
    SystemAccount: string | null;
    VendorReqFlag: string | null;
    VendorSubFlag: string | null;
    ZeroBalance: string | null;
}

export interface InvoiceTransaction {
    BackInvTPId: string | null;
    BHId: string | null;
    BillMethod: string | null;
    BillSeqId: string;
    BillTranId: string;
    BinderPolTEffDate: string | null;
    BinderPostMethod: string | null;
    BinderStatus: string | null;
    BrokerCode: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    ChargeCat: string | null;
    ChargeCode: string | null;
    CoCode: string | null;
    CommPayType: string | null;
    CoType: string | null;
    CSHId: string | null;
    CustId: string | null;
    DatabaseName: string | null;
    Description: string | null;
    EnteredDate: string;
    FullTermPremAmt: Partial<number> | null;
    GLDate: string | null;
    GrossAmt: Partial<number>;
    Id: number;
    InvEffDate: string;
    InvId: string;
    InvTPId: string;
    IsCancelled: string | null;
    IsInstallment: string | null;
    IsPosted: string | null;
    JournalTranId: string | null;
    LineOfBus: string | null;
    NewInvTPId: string | null;
    NonPrRecipient: string | null;
    OldInvTPId: string | null;
    PlanType: string | null;
    PolTEffDate: string | null;
    PolTPId: string | null;
    RBBkOutId: string | null;
    ReplaceDate: string | null;
    TranType: string | null;
    WritingCoCode: string | null;
}

export interface PrCode {
    AttrCode: string | null;
    Category: number;
    ChangedBy: string | null;
    ChangedDate: string;
    Code: string | null;
    DatabaseName: string | null;
    Description: string | null;
    EnteredDate: string;
    EntryId: number;
    Id: number;
    IsHide: string | null;
    PermFlag: number;
    SortNo: number;
}

export interface PolicyTransaction {
    BilledNonPrem: Partial<number>;
    BillMethodPolT: string | null;
    BinderReplacePolTEffDate: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    Description: string | null;
    EffDate: string;
    EnteredDate: string;
    Id: number;
    InstDayPolT: number;
    IsPosted: string | null;
    IsUploaded: string | null;
    PayPId: string | null;
    PolId: string;
    PremOnEffDate: Partial<number> | null;
    ReasonPolT: string | null;
    ReplaceDatePolT: string | null;
    Source: string | null;
    TranType: string | null;
}

export interface CLocation {
    Addr1: string | null;
    Addr2: string | null;
    AnnRevenues: number | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    CLocId: string;
    County: string | null;
    DatabaseName: string | null;
    EffDate: string;
    EnteredDate: string;
    Id: number;
    LocNo: string | null;
    PolId: string;
    State: string | null;
    Status: string | null;
    Zip: string | null;
}

export interface Company {
    Account: string | null;
    AMBestRate: string | null;
    BenefitProviderURL: string | null;
    BJEClosedStatus: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CoCode: string | null;
    DatabaseName: string | null;
    DBStmtAutoMatchAgcyCommAmt: string | null;
    DBStmtAutoMatchGrossAmt: string | null;
    DBStmtAutoMatchLOBChgType: string | null;
    DBStmtAutoMatchPolTEffDate: string | null;
    DBStmtAutoMatchTranType: string | null;
    DBStmtAutoMatchWriteCo: string | null;
    DLSaveData: string | null;
    EnteredDate: string;
    FileCompression: string | null;
    FTPAccount: string | null;
    FTPDirectory: string | null;
    FTPHost: string | null;
    Id: number;
    IsCreateResponse: string | null;
    IsDelSource: string | null;
    IsHide: string | null;
    IsInclAttach: string | null;
    IsPLName: string | null;
    IsStopLoss: string | null;
    NAIC: string | null;
    Name: string | null;
    ParentCoCode: string | null;
    RetainLOB: string | null;
    RetainLOBRwl: string | null;
    ShortName: string | null;
    Status: string | null;
    Type: string | null;
    UsePolUnspecified: string | null;
    UsePriorPolNo: string | null;
    UserId: string | null;
    UWOffice: string | null;
}

export interface CompanyAddress {
    Addr1: string | null;
    Addr2: string | null;
    AddrDesc: string | null;
    AreaCode: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    CoAddId: string;
    CoCode: string | null;
    DatabaseName: string | null;
    EMail: string | null;
    EnteredDate: string;
    Ext: string | null;
    FaxAreaCode: string | null;
    FaxExt: string | null;
    FaxPhone: string | null;
    Id: number;
    IsDefaultChecks: string | null;
    IsDefaultCLForms: string | null;
    IsDefaultPLForms: string | null;
    IsPrimaryAddress: string | null;
    Phone: string | null;
    Phone24HrAreaCodeCoAdd: string | null;
    Phone24HrCoAdd: string | null;
    Phone24HrExtCoAdd: string | null;
    State: string | null;
    Status: string | null;
    WebAddrCoAdd: string | null;
    ZipCode: string | null;
}

export interface CustomerBenefitInfo {
    BusDescr: string | null;
    BusType: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CustId: string;
    DatabaseName: string | null;
    EnteredDate: string;
    EstRev: number | null;
    Id: number;
    Industry: string | null;
    LeadSource: string | null;
    NoOfDeps: number | null;
    NoOfEligEmps: number | null;
    NoOfEmps: number | null;
    SalesProb: number | null;
}

export interface CustomerContact {
    Address1: string | null;
    Address2: string | null;
    BusAreaCode: string | null;
    BusExt: string | null;
    BusPhone: string | null;
    CCntId: string;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    ContactName: string | null;
    County: string | null;
    CustCenterDisplay: string | null;
    CustId: string;
    DatabaseName: string | null;
    EMail: string | null;
    EnteredDate: string;
    FaxAreaCode: string | null;
    FaxExt: string | null;
    FaxPhone: string | null;
    FormalSalutation: string | null;
    Id: number;
    InformalSalutation: string | null;
    IsDirector: string | null;
    IsOfficer: string | null;
    MobileAreaCode: string | null;
    MobileExt: string | null;
    MobilePhone: string | null;
    PagerAreaCode: string | null;
    PagerExt: string | null;
    PagerPhone: string | null;
    ResAreaCode: string | null;
    ResExt: string | null;
    ResPhone: string | null;
    SortOrder: number | null;
    State: string | null;
    Title: string | null;
    Zip: string | null;
}

export interface Customer {
    AcquisitionCode: string | null;
    Active: string | null;
    Addr1: string | null;
    Addr2: string | null;
    ANotId: string | null;
    ARClosedDate: string;
    ARClosedStatus: string | null;
    AutoApplyCR: string | null;
    AutoApplyPay: string | null;
    BillAddr1: string | null;
    BillAddr2: string | null;
    BillCity: string | null;
    BillCounty: string | null;
    BillName: string | null;
    BillState: string | null;
    BillZip: string | null;
    BrokerCode: string | null;
    BusAreaCode: string | null;
    BusExt: string | null;
    BusFullPhone: string | null;
    BusOriginCode: string | null;
    BusPhone: string | null;
    BusSince: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    CollectLetter: string | null;
    CorePersonId: number | null;
    County: string | null;
    CsrCode: string | null;
    CustAddedDate: string | null;
    CustId: string;
    CustNo: number;
    DatabaseName: string | null;
    DBA: string | null;
    DOB: string | null;
    DriversLicense: string | null;
    DUNSNo: string | null;
    EMail: string | null;
    EMail2: string | null;
    EnteredDate: string;
    FaxAreaCode: string | null;
    FaxExt: string | null;
    FaxFullPhone: string | null;
    FaxPhone: string | null;
    FedIdNo: string | null;
    FirmNameCust: string | null;
    FirstName: string | null;
    FormalSalutation: string | null;
    GLBrnchCode: string | null;
    GLDeptCode: string | null;
    GLDivCode: string | null;
    GLGrpCode: string | null;
    GroupingOption: string | null;
    Id: number;
    InformalSalutation: string | null;
    IsBillAddrSameAsCust: string | null;
    IsBillNameSameAsCust: string | null;
    IsBrokCust: string | null;
    IsDeriveAttrFlagsCust: string | null;
    IsExclDelete: string | null;
    IsPrintAgencyBill: string | null;
    IsPrintDirectBill: string | null;
    IsSecured: string | null;
    JoinCriteria: string | null;
    KnownSince: string | null;
    LastName: string | null;
    LateCharge: string | null;
    LatitudeCust: number | null;
    LLId: string | null;
    LongitudeCust: number | null;
    MarineAreaCode: string | null;
    MarineExt: string | null;
    MarineFullPhone: string | null;
    MarinePhone: string | null;
    Married: string | null;
    MasterCustId: string | null;
    MasterSubTrack: string | null;
    MasterSubType: string | null;
    MidName: string | null;
    MktgFlag: string | null;
    NAICS: string | null;
    NonPC: string | null;
    Occupation: string | null;
    OtherAreaCode: string | null;
    OtherExt: string | null;
    OtherFullPhone: string | null;
    OtherPhone: string | null;
    PagerAreaCode: string | null;
    PagerExt: string | null;
    PagerFullPhone: string | null;
    PagerPhone: string | null;
    PermAttrFlagsCust: string | null;
    PremOption: string | null;
    PrintCustStmt: string | null;
    Prod1Code: string | null;
    ReportOption: string | null;
    ResAreaCode: string | null;
    ResExt: string | null;
    ResFullPhone: string | null;
    ResPhone: string | null;
    Sex: string | null;
    SIC: string | null;
    SortName: string | null;
    SSN: string | null;
    State: string | null;
    StatePrintGroup: string | null;
    TypeCust: string | null;
    TypeEntity: string | null;
    TypeName: string | null;
    TypeOfBusiness: string | null;
    UserAttrFlagsCust: string | null;
    WebAddr: string | null;
    YearEmployed: string | null;
    ZipCode: string | null;
}

export interface DefaultAgencyCommission {
    AComId: string;
    ChangedBy: string | null;
    ChangedDate: string;
    CoCode: string | null;
    CommAmt: Partial<number> | null;
    CommMethod: string | null;
    CommPercent: number | null;
    DatabaseName: string | null;
    EffDate: string;
    EnteredDate: string;
    Id: number;
    LineOfBus: string | null;
    LineOfBusSub: string | null;
    State: string | null;
    TranCode: string | null;
    TypeOfBus: number | null;
}

export interface DefaultCommission {
    ChangedBy: string | null;
    ChangedDate: string;
    CoCode: string | null;
    DatabaseName: string | null;
    DComId: string;
    EffDate: string;
    EnteredDate: string;
    FlatAmt: Partial<number> | null;
    Id: number;
    LineOfBus: string | null;
    LineOfBusSub: string | null;
    Method: string | null;
    Percentage: number | null;
    PersCode: string | null;
    RuleType: string | null;
    TranCode: string | null;
    TypeOfBus: number | null;
}

export interface Employee {
    Address1: string | null;
    Address2: string | null;
    BJEClosedStatus: string | null;
    BUAcsId: string | null;
    BusAreaCode: string | null;
    BusExt: string | null;
    BusFullPhone: string | null;
    BusPhone: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    ContactAreaCode: string | null;
    ContactExt: string | null;
    ContactFullPhone: string | null;
    ContactPhone: string | null;
    DatabaseName: string | null;
    DOB: string | null;
    Doc360HotFolderLoc: string | null;
    Doc360HotSpot: string | null;
    EMail: string | null;
    EmergencyContact: string | null;
    EmpCode: string | null;
    EmployeeId: string | null;
    EmpSupervisorCode: string | null;
    EnteredDate: string;
    FaxAreaCode: string | null;
    FaxExt: string | null;
    FaxFullPhone: string | null;
    FaxPhone: string | null;
    FirstName: string | null;
    FullPartTimeInd: string | null;
    HomeAreaCode: string | null;
    HomeExt: string | null;
    HomeFullPhone: string | null;
    HomePhone: string | null;
    Id: number;
    ImageId: string | null;
    ImageType: number | null;
    IsLicensed: string | null;
    IsLimitCustAccess: string | null;
    IsMemoCommissions: string | null;
    IsOther: string | null;
    IsProd: string | null;
    IsRep: string | null;
    IsTeleMarketer: string | null;
    LastName: string | null;
    LogSuspense: string | null;
    MiddleName: string | null;
    MobileAreaCode: string | null;
    MobileExt: string | null;
    MobileFullPhone: string | null;
    MobilePhone: string | null;
    NatlProdCode: number | null;
    PagerAreaCode: string | null;
    PagerExt: string | null;
    PagerFullPhone: string | null;
    PagerPhone: string | null;
    S1099Category: number | null;
    S1099Type: number | null;
    ShortName: string | null;
    SSN: string | null;
    State: string | null;
    Status: string | null;
    Title: string | null;
    TZCode: number;
    YearEmployed: string | null;
    Zip: string | null;
}

export interface Employer {
    Addr1: string | null;
    Addr2: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    CurrOccSince: string | null;
    DatabaseName: string | null;
    EffDate: string;
    EmprId: string;
    EnteredDate: string;
    Id: number;
    Name: string | null;
    PolId: string;
    State: string | null;
    Status: string | null;
    YearsPriorEmp: number | null;
    ZipCode: string | null;
}

export interface CashDisbursment {
    BankCode: string | null;
    CDId: string;
    CDJrnlPostId: string | null;
    CDJrnlPostRefNo: number | null;
    CDJrnlVoidId: string | null;
    CDJrnlVoidRefNo: number | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CheckAmt: Partial<number>;
    CheckDate: string;
    CheckType: string | null;
    DatabaseName: string | null;
    EnteredBy: string | null;
    EnteredDate: string;
    Id: number;
    IsRecurring: string | null;
    IsReviewed: string | null;
    LinkTranId: string | null;
    Memo: string | null;
    PayeeAdd1: string | null;
    PayeeAdd2: string | null;
    PayeeCity: string | null;
    PayeeCode: string | null;
    PayeeId: string | null;
    PayeeOthName: string | null;
    PayeeState: string | null;
    PayeeType: string | null;
    PayeeZip: string | null;
    PCId: string | null;
    ReviewedBy: string | null;
    RIId: string | null;
    RIIterNo: string | null;
    VCId: string | null;
    WaiveLateChargeGJId: string | null;
    WaiveSmallBalanceGJId: string | null;
    WkstnPostDate: string | null;
}

export interface CashReceiptDetail {
    ApprovedBy: string | null;
    BankCode: string | null;
    BankNo: string | null;
    CashType: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CheckNo: string | null;
    CRDId: string;
    CRDReverseId: string | null;
    CRHId: string;
    DatabaseName: string | null;
    Description: string | null;
    EnteredBy: string | null;
    EnteredDate: string;
    Id: number;
    JournalTranId: string | null;
    LinkTranId: string | null;
    Name: string | null;
    NSFGJId: string | null;
    OriginalCRDId: string | null;
    ReceiptAmt: Partial<number> | null;
    ReceiptDate: string;
    ReceiptNo: number | null;
    ReceivedFrom: string | null;
    ReceivedFromCode: string | null;
    ReceivedFromId: string | null;
    ReverseReason: string | null;
    SourceRefNo: number | null;
    ThankYouFlag: string | null;
    WkstnPostDate: string | null;
}

export interface DirectBillDownloadDetail {
    ChangedBy: string | null;
    ChangedDate: string;
    CommRecv: Partial<number>;
    CustId: string;
    DatabaseName: string | null;
    DBDDId: string;
    DBDHId: string;
    DBSHId: string | null;
    EnteredDate: string;
    Gross: Partial<number>;
    Id: number;
    IsDBE: string | null;
    LineOfBus: string | null;
    MatchId: string | null;
    MatchStatus: string | null;
    Method: string | null;
    Percentage: number | null;
    PlanType: string | null;
    PolId: string;
    SortNo: number;
    TranEffDate: string;
    TranType: string | null;
    WritingCoCode: string | null;
}

export interface DirectBillDownloadHeader {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    DBDHId: string;
    EnteredDate: string;
    GLDivCode: string | null;
    Id: number;
    StmtDate: string;
    StmtForCode: string | null;
    StmtForType: string | null;
}

export interface DirectBillEntryHeader {
    ChangedBy: string | null;
    ChangedDate: string;
    CoStmtTotCommRecvStmt: Partial<number>;
    CoStmtTotGross: Partial<number>;
    DatabaseName: string | null;
    DBEHId: string;
    Description: string | null;
    EnteredDate: string;
    GLDate: string | null;
    GLDivCode: string | null;
    Id: number;
    StmtDate: string;
    StmtForCode: string | null;
    StmtForType: string | null;
    StmtStatus: string | null;
    Type4TotCommRecvStmt: Partial<number>;
    Type4TotGross: Partial<number>;
    VoidDate: string | null;
    VoidedBy: string | null;
    VoidReason: string | null;
}

export interface DirectBillEntryDetail {
    ChangedBy: string | null;
    ChangedDate: string;
    ChargeCat: string | null;
    ChargeCode: string | null;
    CustId: string;
    DatabaseName: string | null;
    DBDDId: string | null;
    DBDHId: string | null;
    DBEDId: string;
    DBEHId: string;
    Description: string | null;
    EnteredDate: string;
    Gross: Partial<number>;
    Id: number;
    InvCoId: string | null;
    InvId: string | null;
    InvTPId: string | null;
    LineOfBus: string | null;
    NonPrRecipient: string | null;
    PlanType: string | null;
    PolId: string;
    PolLookupSource: string | null;
    SortNo: number;
    TiComId: string | null;
    TranEffDate: string;
    TranType: string | null;
    WritingCoCode: string | null;
}

export interface DirectBillEntryCommission {
    ChangedBy: string | null;
    ChangedDate: string;
    CommAmt: Partial<number>;
    CommPersCode: string | null;
    CommPersType: string | null;
    CommPremAmt: Partial<number>;
    DatabaseName: string | null;
    DBECId: string;
    DBEDId: string;
    DBEHId: string;
    EnteredDate: string;
    Id: number;
    MemoFlag: string | null;
    Method: string | null;
    NetFlag: string | null;
    OverrideFlag: string | null;
    Percentage: number | null;
    PrimaryFlag: string | null;
}

export interface CashReceiptHeader {
    BankCode: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CRHId: string;
    DatabaseName: string | null;
    DepositDate: string;
    DepositDesc: string | null;
    EnteredDate: string;
    Id: number;
    IsClosed: string | null;
    JournalTranId: string | null;
    PostedBy: string | null;
    PostedDate: string | null;
    PostedJrnlRefNo: number | null;
    TotalPostedAmt: Partial<number>;
}

export interface GeneralLedgerBranch {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    GLBrnchCode: string | null;
    Id: number;
    IsHide: string | null;
    Name: string | null;
    ShortName: string | null;
    Status: string | null;
}

export interface GeneralJournal {
    ApprovedBy: string | null;
    Balance: Partial<number> | null;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    DebitAmt: Partial<number> | null;
    EnteredBy: string | null;
    EnteredDate: string;
    GJId: string;
    GJReverseId: string | null;
    GJrnlPostId: string | null;
    GJrnlPostRefNo: number | null;
    GLDivCode: string | null;
    Id: number;
    IsRecurring: string | null;
    IsReviewed: string | null;
    JEDate: string;
    JEType: number;
    LinkTranId: string | null;
    OriginalGJId: string | null;
    OwnerCode: string | null;
    OwnerFlag: string | null;
    OwnerID: string | null;
    ReverseReason: string | null;
    RIId: string | null;
    RIIterNo: string | null;
    WkstnPostDate: string | null;
}

export interface GeneralLedgerBudgetHeader {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    Description: string | null;
    EnteredDate: string;
    FiscalYear: string | null;
    GLBHId: string;
    GLDivCode: string | null;
    Id: number;
}

export interface GeneralLedgerBudgetDivDept {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    GLBDVId: string;
    GLBHId: string;
    GLBrnchCode: string | null;
    GLDeptCode: string | null;
    GLDivCode: string | null;
    GLGrpCode: string | null;
    Id: number;
    Status: string | null;
}

export interface GeneralLedgerDepartment {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    GLDeptCode: string | null;
    Id: number;
    IsHide: string | null;
    Name: string | null;
    ShortName: string | null;
    Status: string | null;
}

export interface GeneralLedgerBudgetDetail {
    BudgetAmt: Partial<number>;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    FiscalPeriod: string | null;
    GLBDVId: string;
    GLBHId: string;
    GLNumber: string | null;
    Id: number;
}

export interface GeneralLedgerDivision {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    GLDivCode: string | null;
    Id: number;
    IsHide: string | null;
    LateCharge: string | null;
    LCAnnualPercent: number | null;
    LCDaysBefore: number | null;
    LCDesc: string | null;
    LCMinimum: Partial<number> | null;
    LCPeriodFlatRate: Partial<number> | null;
    LCThreshold: Partial<number> | null;
    Name: string | null;
    ShortName: string | null;
    Status: string | null;
}

export interface GeneralLedgerTransaction {
    Archived: boolean;
    AttachId: string | null;
    AttachType: number | null;
    BrokerageCode: string | null;
    BrokerCode: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CommPersCode: string | null;
    CompanyCode: string | null;
    CreditAmt: Partial<number>;
    CustId: string | null;
    DatabaseName: string | null;
    DebitAmt: Partial<number>;
    Description: string | null;
    EnteredDate: string;
    FeeCoCode: string | null;
    FinanceCode: string | null;
    FiscalPeriod: string | null;
    FiscalYear: string | null;
    GLBrnchCode: string | null;
    GLDepartment: string | null;
    GLDivision: string | null;
    GLGrpCode: string | null;
    GLNumber: string | null;
    GLSADefine: number;
    GLTId: string;
    GLTType: number;
    Id: number;
    InvCMBOId: string | null;
    InvCMId: string | null;
    InvCOId: string | null;
    InvCPId: string | null;
    InvId: string | null;
    InvTPId: string | null;
    IsPosted: string | null;
    JournalTranId: string | null;
    PayableCoCode: string | null;
    PolicyId: string | null;
    PSHId: string | null;
    RSHId: string | null;
    S1099Category: number | null;
    S1099Type: number | null;
    SourceJournal: number | null;
    SourceRefNo: number | null;
    SourceTran: number | null;
    TranDate: string | null;
    VendorCode: string | null;
    VInvId: string | null;
    VInvTrId: string | null;
    WaiveLateChargeAmt: Partial<number> | null;
    WaiveSmallBalanceAmt: Partial<number> | null;
}

export interface Invoice {
    ARClosedDate: string;
    ARClosedStatus: string | null;
    BHId: string | null;
    BillMethod: string | null;
    BinderPolTEffDate: string | null;
    BinderPostMethod: string | null;
    BinderStatus: string | null;
    BrokerCode: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    ClosedDate: string;
    ClosedStatus: string | null;
    CSHId: string | null;
    CustId: string | null;
    DatabaseName: string | null;
    DBRecClosedDate: string;
    DueDate: string | null;
    EnteredDate: string;
    ExecCode: string | null;
    GLBrnchCode: string | null;
    GLDeptCode: string | null;
    GLDivCode: string | null;
    GLGrpCode: string | null;
    Id: number;
    InvDate: string | null;
    InvEffDate: string;
    InvId: string;
    InvNo: number;
    InvSeriesId: string;
    InvType: number;
    IsCancelled: string | null;
    IsInstallment: string | null;
    IsPosted: string | null;
    IsPre35Data: string | null;
    JournalTranId: string | null;
    LCDate: string | null;
    OADescription: string | null;
    OAFinanceCode: string | null;
    OAOrigin: number | null;
    OrigDueDate: string | null;
    OriginalInvIdInv: string | null;
    PolId: string | null;
    PolNo: string | null;
    PolRelation: string | null;
    RepCode: string | null;
    VoidInvIdInv: string | null;
}

export interface InvoiceCommission {
    BHId: string;
    BillSeqId: string;
    BillTranId: string;
    ChangedBy: string | null;
    ChangedDate: string;
    CommAmt: Partial<number>;
    CommPersCode: string | null;
    CommPersType: string | null;
    CommPremAmt: Partial<number>;
    CSHId: string | null;
    DatabaseName: string | null;
    EnteredDate: string;
    Id: number;
    InvCMId: string;
    InvCoId: string;
    InvId: string;
    InvTPId: string;
    IsActive: string | null;
    MemoFlag: string | null;
    Method: string | null;
    NetFlag: string | null;
    OverrideFlag: string | null;
    Percentage: number | null;
    PrimaryFlag: string | null;
}

export interface LineOfBusiness {
    AppCreatedDate: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    Description: string | null;
    EffDate: string;
    ElfFormVerId: string | null;
    EnteredDate: string;
    ExpDate: string;
    Id: number;
    InsertSeqNo: number;
    LineOfBus: string | null;
    LOBChangedDate: string | null;
    LOBId: string;
    PlanType: string | null;
    PolId: string;
    SortNo: number | null;
    StatePlanType: string | null;
    UICodeLOBS: string | null;
    WritingCoCode: string | null;
}

export interface LOBSetup {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    DescriptionLOBS: string | null;
    DLAbstractionLOBS: string | null;
    DLProcessingLOBS: number;
    ElfFormTypeId: string | null;
    EnteredDate: string;
    Id: number;
    IdLOBS: number;
    IncomeGrpLOBS: string | null;
    IsBOPLOBS: string | null;
    IsHide: string | null;
    NameLOBS: string | null;
    PermFlagLOBS: number;
    TypeOfBusLOBS: number;
    UICodeLOBS: string | null;
}

export interface Location {
    Addr1: string | null;
    Addr2: string | null;
    AddrSameAsApp: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    County: string | null;
    DatabaseName: string | null;
    EffDate: string;
    EnteredDate: string;
    Id: number;
    Interest: string | null;
    LegalDesc: string | null;
    LobId: string;
    LocId: string;
    LocNo: string | null;
    NoOfUnits: string | null;
    Occupancy: string | null;
    PolId: string;
    ResidenceType: string | null;
    State: string | null;
    Status: string | null;
    Usage: string | null;
    YearBuilt: string | null;
    ZipCode: string | null;
}

export interface MasterAgentTable {
    ChangedBy: string | null;
    ChangedDate: string;
    CoCode: string | null;
    DatabaseName: string | null;
    EnteredDate: string;
    Id: number;
    MagntId: string;
    MasterAgent: string | null;
}

export interface BasicPolInfo {
    AgcyBusClass: string | null;
    ANotId: string | null;
    AuditFlag: string | null;
    AuditPeriod: string | null;
    BillAcctNo: string | null;
    BilledStmtPrem: Partial<number>;
    BillMethod: string | null;
    BrokerCode: string | null;
    BusOriginCode: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CoCode: string | null;
    CompCustNo: string | null;
    CoType: string | null;
    CsrCode: string | null;
    CustId: string;
    DatabaseName: string | null;
    DescriptionBPol: string | null;
    EnteredDate: string;
    ExecCode: string | null;
    FlatAmount: Partial<number> | null;
    FullTermPremium: Partial<number>;
    GLBrnchCode: string | null;
    GLDeptCode: string | null;
    GLDivCode: string | null;
    GLGrpCode: string | null;
    Id: number;
    InstDay: number;
    IsContinuous: string | null;
    IsExclDelete: string | null;
    IsFiltered: string | null;
    IsFinanced: string | null;
    IsMultiEntity: string | null;
    IsNewBPol: string | null;
    IsPosted: string | null;
    IsSuspended: string | null;
    ISTId: string | null;
    MasterAgent: string | null;
    Method: string | null;
    MethodOfPayments: string | null;
    MultiEntityARFlag: string | null;
    NatlProdCode: number | null;
    NegCommValidDate: string | null;
    NumOfPayments: number | null;
    PayPId: string | null;
    Percentage: number | null;
    PolChangedDate: string | null;
    PolEffDate: string | null;
    PolExpDate: string | null;
    PolId: string;
    PolNo: string | null;
    PolSubType: string | null;
    PolType: string | null;
    PolTypeLOB: string | null;
    PremAdj: string | null;
    PriorPolicy: string | null;
    PriorPolId: string | null;
    RenewalList: string | null;
    RenewalRptFlag: string | null;
    ShortPolNo: string | null;
    SourcePolId: string | null;
    Status: string | null;
    SubAgent: string | null;
    TiComId: string | null;
    TypeOfBus: number;
    Underwriter: string | null;
    WritingCoCode: string | null;
}

export interface PolicyPersonnel {
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EmpCode: string | null;
    EmpType: string | null;
    EnteredDate: string;
    FeeFlatAmount: Partial<number> | null;
    FeeMethod: string | null;
    FeePercentage: number | null;
    FlatAmount: Partial<number> | null;
    Id: number;
    IsPrimary: string | null;
    IsSuspended: string | null;
    Method: string | null;
    NegCommFieldScope: string | null;
    Percentage: number | null;
    PolId: string;
    PolPId: string;
}

export interface ProfileAnswer {
    Answer: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    CustId: string;
    DatabaseName: string | null;
    EnteredDate: string;
    Id: number;
    QuestionId: string;
}

export interface ProfileQuestion {
    AnsFormat: string | null;
    AnsLength: number | null;
    ChangedBy: string | null;
    ChangedDate: string;
    DatabaseName: string | null;
    EnteredDate: string;
    Id: number;
    IsHide: string | null;
    Question: string | null;
    QuestionId: string;
    TypeOfBus: number;
}

export interface TableSyncLogEntry {
    DatabaseName: string | null;
    Id: number;
    LastSyncDate: string;
    TableName: string | null;
}

export interface Transaction {
    ChangedBy: string | null;
    ChangedDate: string;
    CoCode: string | null;
    CommentTran: string | null;
    CsrCode: string | null;
    DatabaseName: string | null;
    DBAction: string | null;
    EffDate: string | null;
    EmpCode: string | null;
    EndEffDate: string | null;
    EnteredDate: string;
    EntityId: string | null;
    EntityType: number;
    ExecCode: string | null;
    ExpDate: string | null;
    Id: number;
    PolId: string | null;
    PolNo: string | null;
    PolTypeLOB: string | null;
    RefDate: string | null;
    RefGrChangedBy: string | null;
    RefGrChangedDate: string | null;
    RefGrId: string | null;
    RefId: string | null;
    RefText: string | null;
    RefType: number | null;
    TranDate: string;
    TranId: string;
    TranType: string | null;
}

export interface Underwriter {
    Addr1: string | null;
    Addr2: string | null;
    BusAreaCode: string | null;
    BusExt: string | null;
    BusPhone: string | null;
    ChangedBy: string | null;
    ChangedDate: string;
    City: string | null;
    CoAddId: string | null;
    CoCode: string | null;
    DatabaseName: string | null;
    Department: string | null;
    DOB: string | null;
    EMail: string | null;
    EnteredDate: string;
    FaxAreaCode: string | null;
    FaxExt: string | null;
    FaxPhone: string | null;
    Id: number;
    MobileAreaCode: string | null;
    MobileExt: string | null;
    MobilePhone: string | null;
    Name: string | null;
    PagerAreaCode: string | null;
    PagerExt: string | null;
    PagerPhone: string | null;
    State: string | null;
    Title: string | null;
    UWrtId: string;
    ZipCode: string | null;
}

export interface UvisDirectBillCommission {
    AgcyGross: Partial<number>;
    AgcyPercent: number | null;
    AmtPaidStmt: Partial<number>;
    BillMethod: string | null;
    Carrier: string | null;
    DatabaseName: string | null;
    EmpCode: string | null;
    FirmNameCust: string | null;
    FirstName: string | null;
    Id: number;
    LastName: string | null;
    LineOfBus: string | null;
    MemberName: string | null;
    MidName: string | null;
    PolEffDate: string | null;
    PolExpDate: string | null;
    PolNo: string | null;
    PSDId: string;
    StmtDate: string;
}

export interface UvisUnclaimedPolicy {
    City: string | null;
    CommentTran: string | null;
    DatabaseName: string | null;
    DBAction: string | null;
    EffDate: string | null;
    ExpDate: string | null;
    FirmNameCust: string | null;
    FirstName: string | null;
    Id: number;
    LastName: string | null;
    MidName: string | null;
    Name: string | null;
    PolNo: string | null;
    State: string | null;
    TranDate: string;
    TranId: string;
}

export interface ManualEntryBudget {
    BudgetAmt: Partial<number>;
    DatabaseName: string | null;
    GLDivision: string | null;
    GLNumber: string | null;
    Id: number;
    TranDate: string;
}

export interface ManualEntryGeneralLedger {
    CreditAmt: Partial<number>;
    DatabaseName: string | null;
    DebitAmt: Partial<number>;
    GLDivision: string | null;
    GLNumber: string | null;
    Id: number;
    TranDate: string;
}

export interface ManualEntryProduction {
    CommAmt: Partial<number>;
    DatabaseName: string | null;
    GLDivision: string | null;
    Id: number;
    PersonId: number | null;
    ProducerCodeTypeId: number | null;
    ProductionType: 'New'|'Renew';
    TranDate: string;
}

export interface HistoricalProduction {
    CommAmt: Partial<number>;
    DatabaseName: string | null;
    GLDivision: string | null;
    Id: number;
    TranDate: string;
    TranType: string | null;
}

export interface HistoricalGeneralLedger {
    CreditAmt: Partial<number>;
    DatabaseName: string | null;
    DebitAmt: Partial<number>;
    FiscalPeriod: number;
    FiscalYear: number;
    GLDivision: string | null;
    GLNumber: string | null;
    Id: number;
    TranDate: string;
}

