// ----------------------
// <auto-generated>
//     generated using a custom program
// </auto-generated>
// ----------------------
export interface PersonAdpAccount extends IIdentity {
    AssociateOid: string | null;
    Person: Partial<Person> | null;
}

export interface PersonToNotification extends IIdentity, IExpirable, ICreatedBy {
    Notification: Partial<Notification> | null;
    NotificationDeliveryMethods: Array<Partial<NotificationDeliveryMethod>> | null;
    NotificationId: number;
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonToPeopleGroup extends IIdentity, IExpirable, ISynchronizable {
    PeopleGroup: Partial<PeopleGroup> | null;
    PeopleGroupId: number;
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonToPermissionGroup extends IExpirable, IIdentity {
    PermissionGroup: Partial<PermissionGroup> | null;
    PermissionGroupId: number;
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonToPermission extends IExpirable, IIdentity {
    Permission: Partial<Permission> | null;
    PermissionId: number;
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonName extends IExpirable, IIdentity, ISynchronizable {
    FirstName: string | null;
    LastName: string | null;
    MiddleName: string | null;
    Person: Partial<Person> | null;
    PersonId: number;
    Type: 'Legal'|'Preffered';
}

export interface PersonToAttachmentPermission extends BaseChangeTracking, IIdentity, ISynchronizable {
    Attachment: Partial<Attachment> | null;
    AttachmentId: number;
    CanRead: boolean;
    CanUpdate: boolean;
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonUltiProAccount extends IIdentity, ISynchronizable {
    EeId: string | null;
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonAddress extends Address {
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonLdapAccount extends IIdentity, ISynchronizable {
    Guid: string;
    Person: Partial<Person> | null;
    SamAccountName: string | null;
    Sid: string | null;
}

export interface Person extends IIdentity, ISynchronizable {
    Addresses: Array<Partial<PersonAddress>> | null;
    AdpAccount: Partial<PersonAdpAccount> | null;
    Attachments: Array<Partial<Attachment>> | null;
    Biography: string | null;
    CampaignToCrmAccounts: Array<Partial<CampaignToCrmAccount>> | null;
    CampaignToPeople: Array<Partial<CampaignToPerson>> | null;
    Comments: Array<Partial<Comment>> | null;
    CourseAdmins: Array<Partial<CourseAdmin>> | null;
    CourseMembers: Array<Partial<CourseMember>> | null;
    CourseParticipantStatuses: Array<Partial<CourseParticipantStatus>> | null;
    CourseReportees: Array<Partial<CourseReportee>> | null;
    CreatedAnswers: Array<Partial<EducationAnswer>> | null;
    CreatedCourses: Array<Partial<EducationCourse>> | null;
    CreatedFolders: Array<Partial<Folder>> | null;
    CreatedJobRoleTypes: Array<Partial<JobRoleType>> | null;
    CreatedLessons: Array<Partial<EducationLesson>> | null;
    CreatedOutboundCallerIdNumberGroups: Array<Partial<OutboundCallerIdNumberGroup>> | null;
    CreatedQuestions: Array<Partial<EducationQuestion>> | null;
    CreatedSurveyAnswers: Array<Partial<SurveyAnswer>> | null;
    CreatedSurveyQuestions: Array<Partial<SurveyQuestion>> | null;
    CreatedSurveys: Array<Partial<Survey>> | null;
    CReportComments: Array<Partial<CReportComment>> | null;
    CrmAccounts: Array<Partial<CrmAccount>> | null;
    CrmCommissions: Array<Partial<CrmCommission>> | null;
    DateOfBirth: string | null;
    DeletedAttachments: Array<Partial<Attachment>> | null;
    EloquaEmailTemplateToPeople: Array<Partial<EloquaEmailTemplateToPerson>> | null;
    EmailAddresses: Array<Partial<PersonEmailAddress>> | null;
    Extensions: Array<Partial<Extension>> | null;
    FirstName: string | null;
    ForumAdmins: Array<Partial<ForumAdmin>> | null;
    ForumJoinRequests: Array<Partial<ForumJoinRequest>> | null;
    ForumMembers: Array<Partial<ForumMember>> | null;
    ForumOptOuts: Array<Partial<ForumOptOut>> | null;
    ForumViews: Array<Partial<ForumView>> | null;
    Gender: string | null;
    HomeUserAnalytics: Array<Partial<HomeUserAnalytic>> | null;
    InAppNotifications: Array<Partial<InAppNotification>> | null;
    JobTitle: string | null;
    LastName: string | null;
    LdapAccount: Partial<PersonLdapAccount> | null;
    LessonParticipantStatuses: Array<Partial<LessonParticipantStatus>> | null;
    MessageNotifications: Array<Partial<MessageNotification>> | null;
    Messages: Array<Partial<Message>> | null;
    MiddleName: string | null;
    Names: Array<Partial<PersonName>> | null;
    NewsRecipients: Array<Partial<NewsRecipient>> | null;
    NotificationActivityLogs: Array<Partial<NotificationActivityLog>> | null;
    PersonToNotifications: Array<Partial<PersonToNotification>> | null;
    PersonToPeopleGroups: Array<Partial<PersonToPeopleGroup>> | null;
    PersonToPermissionGroups: Array<Partial<PersonToPermissionGroup>> | null;
    PersonToPermissions: Array<Partial<PersonToPermission>> | null;
    PersonToWebComponentSlides: Array<Partial<PersonToWebComponentSlide>> | null;
    PhoneNumbers: Array<Partial<PersonPhoneNumber>> | null;
    QuickLinks: Array<Partial<QuickLink>> | null;
    Reactions: Array<Partial<Reaction>> | null;
    Replies: Array<Partial<Reply>> | null;
    Reservations: Array<Partial<Reservation>> | null;
    Roles: Array<Partial<PersonRole>> | null;
    SalesExpectations: Array<Partial<SalesExpectation>> | null;
    SurveyAdmins: Array<Partial<SurveyAdmin>> | null;
    SurveyRespondents: Array<Partial<SurveyRespondent>> | null;
    SurveyRespondentStatuses: Array<Partial<SurveyRespondentStatus>> | null;
    SurveyResponses: Array<Partial<SurveyResponse>> | null;
    TrackableAttachmentToPeople: Array<Partial<TrackableAttachmentToPerson>> | null;
    UltiProAccounts: Array<Partial<PersonUltiProAccount>> | null;
}

export interface PersonEmailAddress extends EmailAddress {
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonPhoneNumber extends PhoneNumber {
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface PersonRole extends Role {
    Person: Partial<Person> | null;
    PersonId: number;
}

export interface IIdentity {
    Id: number;
}

export interface IExpirable {
    EndDate: string | null;
    IsExpired: boolean;
    StartDate: string;
}

export interface ICreatedBy {
    CreatorPerson: Partial<Person> | null;
    CreatorPersonId: number;
}

export interface ISynchronizable {
    CreatedDate: string;
    LastModifiedDate: string;
}

export interface IAddress {
    AddressType: 'Business'|'Home'|'TheGamePrize'|'Surge';
    City: string | null;
    Country: string | null;
    County: string | null;
    State: string | null;
    Street1: string | null;
    Street2: string | null;
    Zip: string | null;
}

export interface IPhoneNumber {
    AreaCode: string | null;
    CountryCode: string | null;
    Extension: string | null;
    LineNumber: string | null;
}

