// ----------------------
// <auto-generated>
//     generated using a custom program
// </auto-generated>
// ----------------------

export interface Base64Dto {
    FileName: string | null;
    Value: string | null;
}

export interface NaicsReportTopCarriersDto {
    NaicsCode: number;
    ParentCompany: string | null;
    Premium: number;
    Rank: number;
}

