// ----------------------
// <auto-generated>
//     generated using a custom program
// </auto-generated>
// ----------------------

export interface Base64Dto {
    FileName: string | null;
    Value: string | null;
}

